### ISSUE TITLE
Sending with custom text message with OTP

### ISSUE THREAD

**Issue by sanoj26692** [robinske/serverless-phone-verification#2]
am using this method and it works fine is there any way i can replace with custom `OTP` with a short message.

**Comment by robinske** [comment]
hey there! We offer a `custom code`, but only for sales-engaged customers. If you're interested you can learn more here and reach out to sales: https://www.twilio.com/docs/verify/api/customization-options

We can't offer more customization because our SMS message templates are pre-approved by carriers to reduce filtering and prevent our customers from spamming users with the short codes provided. 

Going to close out this issue, but let me know if you have other questions!

**Comment by sanoj26692** [comment]
Great, I just want to send text messages for phone number verification.

Your site-name.com OTP is : XXXXXX

This is the message template I wanted to use.

**Comment by robinske** [comment]
That's the template the Verify API uses! So you'll be set, set your Service `FriendlyName` to `site-name.com`. More here:

https://www.twilio.com/docs/verify/api/service

Let us know if you run into any issues at help@twilio.com
